#
# Module manifest for module SpListModule
#
# Generated by: Patrick Murphy
#
# Generated on: 10/09/2023
#

@{
    RootModule = 'SpListModule.psm1'
    
    ModuleVersion = '0.1.0'
    
    GUID = '98f81d37-f381-4f25-9552-c0141a7cd444'
    
    Author = 'Patrick Murphy'
    
    PowerShellVersion = '7.0'
    
    FunctionsToExport = 'connectSharePoint','disconnectSharePoint'
    
    PrivateData = @{
        Api = @{
            contextinfo    = "/_api/contextinfo"
            apiWeb         = "/_api/web"
            lists          = "/_api/web/lists"
            items          = "/items"
            item           = "/items({0})"
            orderBy        = "?`$orderby=Created desc&`$top=1&`$select=AuthorId,Id,Title"
            top            = "?`$top=5000"
            skipToken      = "&`$skiptoken=Paged=TRUE%26p_ID={0}"
            siteUsers      = "/siteusers"
            getByTitle     = "/_api/web/lists/GetByTitle('{0}')/Items"
            getByEmail     = "/_api/web/siteusers/getbyemail('{0}')"
            getUserById    = "/_api/web/getuserbyid({0})"
            createListItem = "/_api/web/lists/GetByTitle('{0}')/Items"
            updateListItem = "/_api/web/lists/GetByTitle('{0}')/Items({1})"
            deleteListItem = "/_api/web/lists/GetByTitle('{0}')/Items({1})"
        }
        
        DefaultProperties = @(
            "Id"
            "AuthorId"
            "EditorID"
            "Created"
            "Modified"
        )

        ImportedSPModuleFunctions = @(
            'Invoke-SharePointApi'
            'Convert-SharePointProperties'
            'Get-SharePointAllLists'
            'Get-SharePointListItems'
            'Get-SharePointRequestDigest'
            'Get-SharePointUser'
            'Get-SharePointUserId'
            'New-SharepointListItem'
            'Update-SharepointListItem'
            'Remove-SharepointListItem'
        )

        PSData = @{
            LicenseUri = 'https://mit-license.org/'
    
            ProjectUri = 'https://github.com/nothuslupus/SpListModule'
    
        }
    }  
}